name: Release Github auth-ses-sql-set
on:
  workflow_dispatch:
    branches: [ main ]

  # workflow_run:
  #   branches: [ main ]
  #   workflows: ["Test auth-ses-sql-set"]
  #   types:
  #     - completed
  #   paths: 'packages/public/auth-ses-sql-set/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@juliusagency'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_FROM_REGISTRY }}
     # - run: npm unpublish --force
      - run: |
          npm run build -w packages/private/auth-session \
            -w packages/private/auth-strategies \
            -w packages/private/base-user-mngr \
            -w packages/private/base-user-sql \
            -w packages/public/auth-ses-sql-set --if-present
      - run: npm publish -w packages/public/auth-ses-sql-set
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workspace: "packages/public/auth-ses-sql-set"