name: Test base-user-sql

on:
  workflow_dispatch:
    branches: [ main ]
    paths: 'packages/base-user-sql/**'

  # workflow_run:
  # push:
  #   branches: [ main ]
  #   paths: 'Test base-user-sql'
  # pull_request:
  #   branches: [ main ]
  #   paths: 'packages/base-user-sql/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
