name: Test base-user-mngr

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
    paths: ['packages/base-user-mngr/**']
  # pull_request:
  #   branches: [ main ]
  #   paths: ['packages/base-user-mngr/**']

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci -w packages/base-user-mngr
      - run: npm run build -w packages/base-user-mngr --if-present
      - run: npm test -w packages/base-user-mngr
